### PR TITLE
Add hire page.

### PR DESCRIPTION
**Pull request by neonichu**
I believe you asked for this.

### CODE REVIEW

**Comment by segiddins** [comment]
Time to spam :+1: :)

**Comment by neonichu** [comment]
:+1:

**Comment by Inferis** [comment]
Shouldn't this page include at least *one* animated gif?

**Comment by esttorhe** [comment]
I approve this page :joy:

**Comment by 3lvis** [comment]
:+1:

**Comment by ashfurrow** [comment]
Hello, and thank you for your contribution to this open source project. After consideration, the marketing department found that neither the design nor the content of this page is congruent with the branding guidelines used to cultivate the persona and mystique of Ash Furrow. 

If you would like to contribute to an open source project, we suggest you take a look at the [GitHub Explore](https://github.com/explore) page where you might find a project more suitable for your contributions. Thank you and have a nice day.

**Pull request closed without merging**
