### PR TITLE
New search bar

### LINKED ISSUE #213: Search bar
Hi Ash,

i think that would be great a search functionality in the blog.

-Paolo-

### PR DESCRIPTION
**Pull request by ashfurrow**
Picking up from #232.

Fixes #213.

Doesn't look that fancy yet, needs a bit more polish. Specifically:

- [x] Background image.
- [x] A link to the search page in the nav.
- [x] More whitespace.
- [x] Add thank you links to readme.
- [x] Empty search results.
- [x] Downloading search results spinner or similar (fingers crossed bootstrap has something).
- [x] Something to indicate search index is downloading (nice-to-have).

Current version:

screen shot 2016-08-06 at 8 00 20 pm

Thanks to:

- http://frontendcollisionblog.com/javascript/jekyll/tutorial/2015/03/26/getting-started-with-a-search-engine-for-your-site-no-server-required.html
- https://github.com/manastech/middleman-search

### CODE REVIEW

**Comment by ashfurrow** [comment]
Better:

screen shot 2016-08-06 at 9 40 33 pm

**Comment by ashfurrow** [comment]
I've disabled asset hashes since I'm not on Amazon S3 anymore and aren't using year-long cache lifetimes anymore.

**Comment by ashfurrow** [comment]
@orta this looks okay to me, nothing that fancy. Fun to build, too. Worth it & ready to ship you reckon?

**Comment by orta** [comment]
Yep, glad you changed the vertical spacing - was going to comment on that.

This is all surprisingly simple.

**Comment by orta** [comment]
Looks great IMO - shippit

**Pull request merged**
