### PR TITLE
Update 2014-09-09-shooting-film.markdown

### PR DESCRIPTION
**Pull request by ncoreys28**
Adding Artsy url to second mention of ansel adams.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool! So a few quick things:

First, the Travis problem ("Failed" and the red X there) are *not* your fault. Travis is having problems. Again. So ignore that. 

Second, this is a markdown file, so we can avoid the HTML syntax. Instead, you can make a link like this:

```markdown
[Ansel Adams](https://www.artsy.net/artist/ansel-adams)
```

Finally, let's take out the link you added and instead replace the link to Wikipedia with the Artsy link. Does that make sense? 

To make changes, go to your fork, and where it says `master`, select `patch-1`:

screen shot 2015-03-16 at 10 54 31 am

Then find the same file, and make the changes directly through GitHub. The changes will be automatically added to this pull request. 

:cake:

**Comment by ncoreys28** [comment]
Tried using suggested syntax, and could not get it hyperlinked.

**Comment by ashfurrow** [comment]
How do you mean? In the text file, GitHub won't make it look like a hyperlink while you're editing it or looking at the raw file. It looks like everything is fine, and if you look at the file in your branch ( https://github.com/ncoreys28/blog/blob/patch-1/source/blog/2014-09-09-shooting-film.markdown ), then it looks :+1:

screen shot 2015-03-16 at 11 07 39 am

I'll wait for Travis to go green before merging, but this looks great!

**Comment by ashfurrow** [comment]
Hopefully I fixed travis being stupid in this commit: https://github.com/ashfurrow/blog/commit/62032db43c6a43cb5944a175418a9a9eb68c68bc So I'm gonna merge.

**Pull request merged**
