### PR TITLE
Archives Page

### LINKED ISSUE #156: No archives page
I wanted to look over all the titles of your blog posts at one go, couldn't find it, so I switch to using google

### PR DESCRIPTION
**Pull request by ashfurrow**
So _obviously_ I'm going for a direct rip-off of @ole's archives page: http://oleb.net/blog/ Things I still need left:

- [x] ~~Link to RSS feed.~~
- [x] ~~Spacing could be better/more consistent.~~
- [x] ~~Background header image?~~
- [ ] Re-verify with Google Webmaster Tools.
- [ ] Remove `/page/1`, `/page/2/` etc from Google's index to prevent crawl errors. Maybe a redirect rule in AWS.
- [x] The :+1: from @orta.

Fixes #156.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Deploy to staging finished: http://staging.ashfurrow.com/blog/

**Comment by ole** [comment]
@ashfurrow 👍

**Comment by orta** [comment]
You've wrote so much. I definitely prefer this, I used to use google to find old posts of yours. :+1: 

Optional: you could skip the date if two blog posts on the same date

before
screen shot 2015-10-17 at 16 32 06

after
screen shot 2015-10-17 at 16 33 18

**Comment by ashfurrow** [comment]
Neat idea – thanks!

**Pull request merged**
