### PR TITLE
Transitioned Speaking page to use yml

### LINKED ISSUE #41: Use More Yaml
Like [here](https://github.com/ashfurrow/blog/blob/1fc6756717f9a6ff5fabb43e8b622fab8deedee2/source/speaking.html.erb#L70-L73). 

/via @orta

### PR DESCRIPTION
**Pull request by ashfurrow**
On @orta's suggestion, I've transitioned from custom Ruby objections to using YAML, a much more expressive data description format. Also cleaned up some code and added ITT/UIKonf/dotSwift. 

Fixes #41.

### CODE REVIEW

**Comment by orta** [comment]
Rockin

**Comment by orta** [comment]
You and your belief in no white spacing :palm_tree:

**Comment by ashfurrow** [comment]
How so?

**Comment by orta** [comment]
https://github.com/ashfurrow/blog/blob/master/data/talks.yml#L12-L93

vs 

https://github.com/artsy/artsy.github.com/blob/source/artsy-oss.yml

**Comment by ashfurrow** [comment]
I have a whitespace, see? https://github.com/ashfurrow/blog/blob/a671e91bdf914953dce302ac235c0958f865b016/data/talks.yml#L11

**Comment by orta** [comment]
Giphy

**Pull request merged**
