### PR TITLE
Rakefile updates

### LINKED ISSUE #222: Rake task for PRs
Since I'm putting new articles in PRs lately, a `rake pr` command to push and open the "new pr" web address appropriate for the branch would be handy.

### LINKED ISSUE #223: Customize proselint settings
screen shot 2016-07-10 at 8 39 20 pm

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #222. Fixes #223.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Ok, weird. Same error as before. Tracing it down, looks like [`parse`](https://github.com/danger/danger/blob/v2.1.0/lib/danger/danger_core/dangerfile.rb#L161) is getting called with a sample Dangerfile. Further up the stack [this line](https://github.com/danger/danger/blob/v2.1.0/lib/danger/danger_core/executor.rb#L46) calls `parse` with a Dangerfile it's just downloaded from `dm.env.request_source.file_url(repository: danger_repo.name, path: "Dangerfile")`. @orta have you seen this? Looks plugin-related, but I can't tell the purpose of it.

**Comment by ashfurrow** [comment]
Weird, the two lines it complains about are [similar to danger/danger's Dangerfile](https://github.com/danger/danger/blob/372af6e4929954f019229e2b579378598a651075/Dangerfile#L3-L4) (they're missing the `git.` in front of some methods, causing this problem. I'm going to try rebuilding without cache, maybe it's pointing to an outdated file, though I don't really understand what's going on.

**Comment by ashfurrow** [comment]
Looks like that line of code was added in https://github.com/danger/danger/commit/caff2a6e73a9e385cef1dd2ac0dd501734ea33ae two days ago, falling back to the most recent version of Danger before that commit.

**Comment by ashfurrow** [comment]
Okay, I think what's happening is that Danger is interpreting my GH user as an organization, notices I have an `ashfurrow/danger` repo (a fork, outdated) and downloading the Dangerfile from there (which no longer works). I've deleted the fork and going to see if that fixes things. Will open an issue once I confirm the fix.

**Comment by orta** [comment]
There is an issue open about that, needs to check for a danger.gemspec

**Comment by ashfurrow** [comment]
Looks like this is a slightly different issue, since `ashfurrow/danger` is not meant to be an org-wide Danger repo, but just a fork. [There's an issue open](https://github.com/danger/danger/issues/366) for that situation too 👍

**Pull request merged**
