### PR TITLE
Adds Danger

### LINKED ISSUE #216: Integrate spellchecker?
https://www.npmjs.com/package/markdown-spellcheck

From https://github.com/artsy/artsy.github.io/issues/232

### PR DESCRIPTION
**Pull request by ashfurrow**
Adds [Danger] to the repo. Fixes #216.

Basically just copied the Dangerfile from Artsy's blog. There was a todo to turn that into a proper plugin, probably best to get up and running on Danger dev in-person with @orta, so I left it for now.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Something depending on ffi crapped out, which [is apparently still not fixed](https://github.com/ffi/ffi/issues/461). Maybe it's time to look into that some more to see if it _has_ been fixed.

**Comment by orta** [comment]
Weird, not sure offhand

**Comment by ashfurrow** [comment]
Appears to be building now. Trick was to add the aspell apt packages in https://github.com/ashfurrow/blog/pull/217/commits/e51eb7f58c4ef931836c2034041aefa7667b2bec (based on the bug report at https://github.com/travis-ci/travis-ci/issues/3368 )

**Comment by orta** [comment]
Magic ✨

**Pull request merged**
